version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: marathon
    ports:
      - "8080:80"
  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - /docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app