services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marathon
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:
    external: true
    # ports:
    #   - "8080:80"
